### ISSUE TITLE
Beim Aufruf des Profile wird eine Exception erzeugt

### ISSUE THREAD

**Issue by Napo1111** [Niels1303/IWMB02#1]
D/OpenGLRenderer: endAllActiveAnimators on 0x923a3480 (MenuPopupWindow$MenuDropDownListView) with handle 0x9257f8a0
D/AndroidRuntime: Shutting down VM
****E/AndroidRuntime: FATAL EXCEPTION: main**
    Process: iwmb02.com.iwmb02, PID: 15040
    java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
        at iwmb02.com.iwmb02.view.Profile$2.onResponse(Profile.java:158)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
Application terminated.**

**Comment by Napo1111** [comment]
Der Fehler tritt auf sobald ich (egal in welchem Fragment) auf das Profile gehe

**Comment by Napo1111** [comment]
Der Fehler tritt auf sobald das Profile (egal von welchem Fragment) aufgerufen wird.

**Comment by Napo1111** [comment]
In der dick gedruckten Zeile 158 scheint das Problem zu liegen:
mAdapter = new ProfileListAdapter(Profile.this);
                            mAdapter.addSectionHeaderItem("My Profile");
                            **mAdapter.addItem("Username: " + joinUserBrettspiele[0].getUser().getUsername());**
                            mAdapter.addItem("Real name: " + joinUserBrettspiele[0].getUser().getVorname() + " " + joinUserBrettspiele[0].getUser().getNachname());
                            mAdapter.addItem("Amount of hosted Game Nights: " + joinUserBrettspiele[0].getUser().getAusrichterCounter().toString());
                            mAdapter.addItem("Amount of joined Game Nights: " + joinUserBrettspiele[0].getUser().getTeilnehmerCounter().toString());
                            mAdapter.addSectionHeaderItem("My Boardgames");
                            int length = Array.getLength(joinUserBrettspiele);
                            for (int i = 0; i < length; i++) {
                                mAdapter.addItem(joinUserBrettspiele[i].getBrettspiel().getName());

**Comment by Niels1303** [comment]
Habe das Problem gefunden. Es lag daran, dass ich kein "ArrayOutOfBound" abgefangen hatte, falls einem User noch keine Brettspiele anhand der "joinUserBrettspiel" Tabelle zugewiesen wurden.

**Comment by Niels1303** [comment]
Hatte doch noch etwas übersehen. Jetzt sollte es aber nicht mehr abstürtzen.
